#!/usr/bin/env python

from optparse import OptionParser

from buxfer_commands.show_balance import ShowBalance
from buxfer_commands.daemon import BuxferDaemon

parser = OptionParser()
parser.add_option('-s', '--show-balance', dest='show_balance',
    help='Show accounts balance', action='store_false')
parser.add_option('-d', '--daemon', dest='daemon',
    help="Launch process as daemon", action='store_false')


(options, args) = parser.parse_args()

if options.daemon is None and \
    options.show_balance is None:
    parser.print_help()
elif options.daemon is False and \
    options.show_balance is False:
    print "Can't use daemon and balance at the same time"
elif options.daemon is None and \
    options.show_balance is False:
    sb = ShowBalance()
    sb.show_accounts()
elif options.daemon is False and \
    options.show_balance is None:
    bd = BuxferDaemon()
    bd.send_report()